### ISSUE TITLE
Inconsistent results in the published paper and the repo

### ISSUE THREAD

**Issue by nothingelse92** [Majiker/BalancedMetaSoftmax-InstanceSeg#4]
In the original paper, the reported results of LVIS in Table 4: APm = 27.0 and APb = 27.6 , while in this repo, APm = 27.0 and APb = 26.4

**Comment by cunjunyu** [comment]
Thanks for raising the question.

For the result in the original paper, we obtained it using an internal framework that is only for internal usage and cannot be open-sourced due to the company's policy.  Thus, we choose a popular codebase, detectron2 as the platform to open-source code.

The result cannot be matched exactly due to different implementation details. The result would also be quite different if you take [mmdetection](https://github.com/open-mmlab/mmdetection) as the code-base. We only tune the configuration to match the major metric used in LVIS, AP mask, in detectron2 for open-source purposes. One may further tune the configuration in order to obtain a better result on LVIS. 

Thank you.

**Comment by cunjunyu** [comment]
I will close the issue for now. Feel free to reopen it if you have any further questions.
